# 관리자 권한 갖기
sudo: required

#언어(플램폿)선택
language: generic

#도커 환경 구성
services:
  - docker

#스크립트를 실행할 수 있는 환경
before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t tinywind/react-firebase-messaging-app -f Dockerfile.dev .

#실행할 스크립트
script:
  - docker run -e CI=true tinywind/react-firebase-messaging-app npm run test -- --coverage

#테스트 성공 후
after_success:
  - echo "Test Success"
